=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/commission.schema.json
{
    "$schema" : "https://json-schema.org/draft/2020-12/schema",
    "$id" : "commission.schema.json",
    "title" : "Commission",
    "description": "A Commission in the Building Journal",
    "type": "object",
    "properties": {
        "$schema" : {
            "description": "This current Schema",
            "type" : "string"
        },
        "schemaVersion" : {
            "description": "Schema version",
            "$ref": "#/$defs/schema_version"
        },
        "id" : {
            "description": "Unique Identifier of the Commission",
            "type" : "string"
        },
        "title" : {
            "description": "Title of the Commission",
            "type" : "string"
        },
        "thumbnailPath" : {
            "description": "Path to the thumbnail of the Commission",
            "type" : "string"
        },
        "conditions": {
            "description": "Conditions required to satisfy the Commission",
            "type" : "array",
            "minItems": 1,
            "items" : {
                "type" : "object",
                "properties": {
                    "title" : {
                        "description": "What the condition is called in-game",
                        "type" : "string"
                    },
                    "condition" : {
                        "description": "The condition type",
                        "$ref": "#/$defs/condition"
                    },
                    "failureDescription" : {
                        "description": "What to tell the player if the condition fails",
                        "type": "string"
                    }
                },
                "allOf": [
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "BlockAdded"}
                            }
                        },
                        "then": {
                            "properties": {
                                "blocks" : {
                                    "description": "Block ids to check",
                                    "type": "array",
                                    "items" : {
                                        "type": "string"
                                    }
                                },
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">", "=="]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "integer"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "BlockRemoved"}
                            }
                        },
                        "then": {
                            "properties": {
                                "blocks" : {
                                    "description": "Block ids to check",
                                    "type": "array",
                                    "items" : {
                                        "type": "string"
                                    }
                                },
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">", "=="]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "integer"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "BlockModified"}
                            }
                        },
                        "then": {
                            "properties": {
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">", "=="]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "integer"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "Density"}
                            }
                        },
                        "then": {
                            "properties": {
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">", "=="]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "number"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "Dimension"}
                            }
                        },
                        "then": {
                            "properties": {
                                "dimensions" : {
                                    "description": "Dimensions allowed",
                                    "type": "array",
                                    "items" : {
                                        "type": "string"
                                    },
                                    "minItems": 1
                                }
                            },
                            "required": ["dimensions"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "Elevation"}
                            }
                        },
                        "then": {
                            "properties": {
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">"]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "integer"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "Length"}
                            }
                        },
                        "then": {
                            "properties": {
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">", "=="]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "integer"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "Tallness"}
                            }
                        },
                        "then": {
                            "properties": {
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">", "=="]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "integer"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "TotalVolume"}
                            }
                        },
                        "then": {
                            "properties": {
                                "operator" : {
                                    "description": "Comparison operator",
                                    "enum": ["<", ">", "=="]
                                },
                                "threshold" : {
                                    "description": "Value to compare against",
                                    "type": "integer"
                                }
                            },
                            "required": ["operator", "threshold"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "Whitelist"}
                            }
                        },
                        "then": {
                            "properties": {
                                "blocks" : {
                                    "description": "Block ids to check",
                                    "type": "array",
                                    "minItems": 1,
                                    "items" : {
                                        "type": "string"
                                    }
                                },
                                "isBlacklist" : {
                                    "description": "Is this a blacklist? By default this is false.",
                                    "type": "boolean"
                                }
                            },
                            "required": ["blocks"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "condition" : { "const" : "Biome"}
                            }
                        },
                        "then": {
                            "properties": {
                                "biomes" : {
                                    "description": "Biomes required",
                                    "type": "array",
                                    "minItems": 1,
                                    "items" : {
                                        "type": "string"
                                    }
                                }
                            },
                            "required": ["biomes"]
                        }
                    }
                ],
                "unevaluatedProperties": false,
                "required" : ["condition"]
            }
        },
        "unlocks": {
            "description": "What the Commission unlocks once completed",
            "type" : "array",
            "items" : {
                "type" : "object",
                "properties": {
                    "title": {
                        "description": "What the unlock is called in-game",
                        "type" : "string"
                    },
                    "unlock" : {
                        "description": "The unlock type",
                        "$ref": "#/$defs/unlock"
                    }
                },
                "allOf": [
                    {
                        "if" : {
                            "properties": {
                                "unlock" : { "const" : "BlockReward"}
                            }
                        },
                        "then": {
                            "properties": {
                                "block" : {
                                    "description": "The block ID",
                                    "type": "string"
                                },
                                "count" : {
                                    "description": "Number of blocks rewarded",
                                    "type": "integer"
                                }
                            },
                            "required": ["block", "count"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "unlock" : { "const" : "ExpReward"}
                            }
                        },
                        "then": {
                            "properties": {
                                "expAmount" : {
                                    "description": "The amount of exp rewarded",
                                    "type": "integer"
                                },
                                "expType" : {
                                    "description": "Whether the amount is in levels or points",
                                    "enum" : ["Points", "Levels"]
                                }
                            },
                            "required": ["expAmount", "expType"]
                        }
                    },
                    {
                        "if" : {
                            "properties": {
                                "unlock" : { "const" : "CommissionReward"}
                            }
                        },
                        "then": {
                            "properties": {
                                "commission" : {
                                    "description": "The commission ID",
                                    "type": "string"
                                }
                            },
                            "required": ["commission"]
                        }
                    }
                ],
                "unevaluatedProperties": false,
                "required" : ["unlock"]
            }
        },
        "prerequisites": {
            "description": "What's required to be completed to unlock this Commission",
            "type" : "array",
            "items" : {
                "type" : "string"
            }
        }
    },
    "required" : ["schemaVersion", "title", "conditions"],
    "unevaluatedProperties": false,

    "$defs": {
        "schema_version" : {
            "enum": [1]
        },
        "condition" : {
            "enum" : ["BlockAdded", "BlockModified", "BlockRemoved", "Density", "Dimension", "Elevation", "Length", "Tallness", "TotalVolume", "Whitelist", "Biome"]
        },
        "unlock" : {
            "enum" : ["BlockReward", "ExpReward", "CommissionReward"]
        }
    }
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/fishing_dock.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "Fishing Dock",
    "thumbnailPath": "fishing_dock.png",
    "prerequisites": ["your_first_house", "farmland", "mineshaft_entrance"],
    "conditions": [
        {"title": "Build your dock near a water body!", "condition": "Biome", "biomes": ["#minecraft:is_deep_ocean", "#minecraft:is_ocean", "#minecraft:is_beach", "#minecraft:is_river"], "failureDescription": "You've not built near a water body!"},
        {"title": "Have the gangway be at least 10 blocks long.", "condition": "Length", "operator": ">", "threshold": 9, "failureDescription": "The dock is not long enough!"},
        {"title": "Wood is the best material for docks!", "condition": "BlockAdded", "blocks": ["#minecraft:planks", "#minecraft:logs"], "operator": ">", "threshold": 0, "failureDescription": "No wood logs or planks found!"},
        {"title": "Barrels help store fish!", "condition": "BlockAdded", "blocks": ["minecraft:barrel"], "operator": ">", "threshold": 0, "failureDescription": "No barrels found!"}
    ],
    "unlocks": [
        {"unlock": "ExpReward", "expType": "Levels", "expAmount": 5}
    ]
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/your_first_house.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "Your First House",
    "conditions": [
        {"title": "Add less than 100 blocks", "condition": "BlockAdded", "operator": "<", "threshold": 100},
        {"condition": "BlockRemoved", "operator": ">", "threshold": 400},
        {"condition": "Elevation", "operator": "<", "threshold": 64, "failureDescription": "Too high up! Is at {current_elevation}, must be at 64 or lower."}
    ],
    "unlocks": [
        {"title": "Stone", "unlock": "BlockReward", "block": "minecraft:stone", "count": 32}
    ]
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/home_at_the_end.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "Home at the End",
    "thumbnailPath": "home_at_the_end.png",
    "prerequisites": ["smithy", "fishing_dock", "nether_portal"],
    "conditions": [
        {"title": "You've beaten the game (hopefully!). Build a new home at the end.", "condition": "Dimension", "dimensions": ["minecraft:the_end"], "failureDescription": "Your base is not at the end!"},
        {"title": "Use the end stone everywhere to make bricks for the house! Use at least 100.", "condition": "BlockAdded", "blocks": ["minecraft:end_stone_bricks", "minecraft:end_stone_brick_stairs", "minecraft:end_stone_brick_slab", "minecraft:end_stone_brick_wall"], "operator": ">", "threshold": 99, "failureDescription": "Not enough end stone bricks used! Only {value} has been added."},
        {"title": "The chorus fruits give you purpur blocks! Add a 100 of those too.", "condition": "BlockAdded", "blocks": ["minecraft:purpur_block", "minecraft:purpur_pillar", "minecraft:purpur_slab", "minecraft:purpur_stairs"], "operator": ">", "threshold": 99, "failureDescription": "Not enough purpur blocks used! Only {value} has been added."},
        {"title": "Make some end rods for light!", "condition": "Whitelist", "blocks": ["minecraft:end_rod"], "failureDescription": "No end rods found!"}
    ],
    "unlocks": [
        {"unlock": "ExpReward", "expType": "Levels", "expAmount": 10}
    ]
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/smithy.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "Smithy",
    "thumbnailPath": "smithy.png",
    "prerequisites": ["your_first_house", "farmland", "mineshaft_entrance"],
    "conditions": [
        {"title": "A smithy needs lava!", "condition": "BlockAdded", "blocks": ["minecraft:lava", "minecraft:lava_cauldron"], "operator": ">", "threshold": 0, "failureDescription": "No lava found!"},
        {"title": "A smithy needs to let out fumes high up!", "condition": "Tallness", "operator": ">", "threshold": 9, "failureDescription": "Your smithy is not tall enough! Make it at least 10 blocks high, not {value}."},
        {"title": "Don't use cobblestone,",  "condition": "Whitelist", "blocks": ["minecraft:stone", "minecraft:cobblestone"], "isBlacklist": true, "failureDescription": "{value} is not allowed!"},
        {"title": "Use deepslate instead! Use at least 100 full blocks.",  "condition": "BlockAdded", "blocks": ["minecraft:deepslate", "minecraft:cobbled_deepslate", "minecraft:polished_deepslate", "minecraft:deepslate_tiles", "minecraft:deepslate_bricks", "minecraft:chiseled_deepslate"], "operator": ">", "threshold": 99, "failureDescription": "{value} blocks is not enough deepslate!"},
        {"title": "Bricks keep you safe from the lava.",  "condition": "BlockAdded", "blocks": ["minecraft:bricks"], "operator": ">", "threshold": 7, "failureDescription": "Make sure to have at least 8 bricks!"},
        {"title": "Smithy need blast furnaces,", "condition": "BlockAdded", "blocks": ["minecraft:blast_furnace"], "operator": ">", "threshold": 0, "failureDescription": "No blast furnace found!"},
        {"title": "Anvils,",  "condition": "BlockAdded", "blocks": ["#minecraft:anvil"], "operator": ">", "threshold": 0, "failureDescription": "No anvils found!"},
        {"title": "And smithing tables to operate!",  "condition": "BlockAdded", "blocks": ["minecraft:smithing_table"], "operator": ">", "threshold": 0, "failureDescription": "No smithing table found!"}
    ]
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/villager_trading_hall.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "Villager Trading Hall",
    "thumbnailPath": "villager_trading_hall.png",
    "prerequisites": ["smithy", "fishing_dock", "nether_portal"],
    "conditions": [
        {"title": "A trading hall needs to be big and spacious, at least 800 blocks in volume.", "condition": "TotalVolume", "operator": ">", "threshold": 800, "failureDescription": "The hall is only {value} blocks in volume!"},
        {"title": "You need to have plenty of beds. Place at least 6.", "condition": "BlockAdded", "blocks": ["#minecraft:beds"], "operator": ">", "threshold": 5, "failureDescription": "Not enough beds!"},
        {"title": "Each villager you're trading with needs a profession! Have at least 5.", "condition": "BlockAdded", "blocks": ["minecraft:barrel", "minecraft:blast_furnace", "minecraft:brewing_stand", "minecraft:cartography_table", "#minecraft:cauldrons", "minecraft:composter", "minecraft:grindstone", "minecraft:fletching_table", "minecraft:lectern", "minecraft:loom", "minecraft:smithing_table", "minecraft:smoker", "minecraft:stonecutter"],
        "operator": ">", "threshold": 4, "failureDescription": "Not enough blocks that give villagers their profession!"},
        {"title": "Have enough chests or barrels for storage!", "condition": "BlockAdded", "blocks": ["minecraft:chest", "minecraft:barrel"], "operator": ">", "threshold": 0, "failureDescription": "No chests found!"},
        {"title": "Make an enchanting table here as well!", "condition": "Whitelist", "blocks": ["minecraft:enchanting_table"], "failureDescription": "No enchanting table found!"},
        {"title": "An enchanting table needs bookshelves to work well! Have at least 10 around it, but the best enchants need 15.", "condition": "BlockAdded", "blocks": ["minecraft:bookshelf"], "operator": ">", "threshold": 9, "failureDescription": "Not enough bookshelves!"}
    ]
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/farmland.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "Farmland",
    "thumbnailPath": "farmland.png",
    "conditions": [
        {"title": "Have at least 100 farmland tiles!", "condition": "BlockAdded", "blocks": ["minecraft:farmland"], "operator": ">", "threshold": 99, "failureDescription": "Only {value} farmland tiles found!"},
        {"title": "Fence it up! Use a stack at least.",  "condition": "BlockAdded", "blocks": ["#minecraft:fences"], "operator": ">", "threshold": 63, "failureDescription": "Not enough fences! Currently only {value} present."},
        {"title": "Water is important..",  "condition": "BlockAdded", "blocks": ["minecraft:water"], "operator": ">", "threshold": 0, "failureDescription": "No water found!"},
        {"title": "... and so is light!", "condition": "BlockAdded",
        "blocks": ["minecraft:torch", "minecraft:wall_torch", "minecraft:redstone_torch", "minecraft:redstone_wall_torch",
                   "minecraft:jack_o_lantern", "minecraft:sea_lantern", "minecraft:lantern", "minecraft:soul_lantern", "minecraft:redstone_lamp"],
        "operator": ">", "threshold": 0, "failureDescription": "Light up the farm!"},
        {"title": "A composter is helpful!",  "condition": "BlockAdded", "blocks": ["minecraft:composter"], "operator": ">", "threshold": 0, "failureDescription": "You need to place down a composter!"}
    ],
    "unlocks": [
        {"unlock": "ExpReward", "expType": "Levels", "expAmount": 1}
    ]
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/nether_portal.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "Nether Portal",
    "thumbnailPath": "nether_portal.png",
    "prerequisites": ["your_first_house", "farmland", "mineshaft_entrance"],
    "conditions": [
        {"title": "A nether portal needs at least 10 blocks of obsidian,", "condition": "BlockAdded", "blocks": ["minecraft:obsidian"], "operator": ">", "threshold": 9, "failureDescription": "Not enough obsidian for a portal!"},
        {"title": "That is at least 5 blocks tall,", "condition": "Tallness", "operator": ">", "threshold": 4, "failureDescription": "The portal is not tall enough!"},
        {"title": "And 4 blocks wide!", "condition": "Length", "operator": ">", "threshold": 3, "failureDescription": "The portal is not wide enough!"},
        {"title": "But don't just make the frame; Decorate, add walls! At least 100 blocks' worth.", "condition": "BlockModified", "operator": ">", "threshold": 99,  "failureDescription": "You haven't decorated enough! Only {value} blocks have been modified."}
    ],
    "unlocks": [
        {"unlock": "ExpReward", "expType": "Levels", "expAmount": 5}
    ]
}

=== Pointless-Building-Corporation/Building-Journal/src/main/resources/commissions/fortress_operating_base.json
{
    "$schema" : "commission.schema.json",
    "schemaVersion": 1,
    "title": "FOB (Fortress Operating Base)",
    "thumbnailPath": "fortress_operating_base.png",
    "prerequisites": ["smithy", "fishing_dock", "nether_portal"],
    "conditions": [
        {"title": "It goes without saying, build in the nether!", "condition": "Dimension", "dimensions": ["minecraft:the_nether"], "failureDescription": "Your base is not in the nether!"},
        {"title": "Use nether bricks for the house! At least 200 blocks.", "condition": "BlockAdded", "blocks": ["minecraft:nether_bricks", "minecraft:nether_brick_fence", "minecraft:nether_brick_stairs"], "operator": ">", "threshold": 199, "failureDescription": "Only {value} nether bricks found!"},
        {"title": "For wood, use the trees from the nether!", "condition": "BlockAdded", "blocks": ["#minecraft:warped_stems", "#minecraft:crimson_stems", "minecraft:crimson_planks", "minecraft:warped_planks"], "operator": ">", "threshold": 0, "failureDescription": "No nether tree-based blocks found!"}
    ]
}
